on: [push, pull_request]

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn

    - name: Run ESLint check
      run: npx eslint .

  Tests:
    runs-on: ubuntu-latest
    needs: [ESLint]
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn

    - name: Run tests
      run: yarn test:ci